unit TestCIM.Entity;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, CIM.System.Persistence.Attributes, CIM.Entity.Kwaliteit,
  CIM.System.NotNullable, UntCIMSystemTypes, CIM.Entity.Artikel,
  CIM.System.EntAudit, CIM.System.Nullable, CIM.System.Persistence.Proxy,
  CIM.Entity.User, CIM.Entity.Code, CIM.Entity.Order, CIM.Entity.BatchRegistratie,
  CIM.Entity.WorkStation, CIM.Entity.Batch, CIM.Entity.ProductieStap;

type
  // Test methods for class TEntArtikel

  TestTEntArtikel = class(TTestCase)
  strict private
    FEntArtikel: TEntArtikel;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;
  // Test methods for class TEntBatchRegistratie

  TestTEntBatchRegistratie = class(TTestCase)
  strict private
    FEntBatchRegistratie: TEntBatchRegistratie;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTEntArtikel.SetUp;
begin
  FEntArtikel := TEntArtikel.Create;
end;

procedure TestTEntArtikel.TearDown;
begin
  FEntArtikel.Free;
  FEntArtikel := nil;
end;

procedure TestTEntBatchRegistratie.SetUp;
begin
  FEntBatchRegistratie := TEntBatchRegistratie.Create;
end;

procedure TestTEntBatchRegistratie.TearDown;
begin
  FEntBatchRegistratie.Free;
  FEntBatchRegistratie := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTEntArtikel.Suite);
end.

