program Concepts;

{$I Concepts.inc}

uses
  {$IFDEF FASTMM}
  FastMM4 in 'Libraries\fastmm\FastMM4.pas',
  FastMM4Messages in 'Libraries\fastmm\FastMM4Messages.pas',
  {$ENDIF }
  Vcl.Themes,
  Vcl.Styles,
  Vcl.Forms,
  {$IFNDEF HAS_UNIT_SYSTEM_IMAGELIST}
  System.ImageList in 'Types\System.ImageList.pas',
  {$ENDIF }
  {$IFDEF BTMEMORYMODULE}
  BTMemoryModule in 'Libraries\BTMemoryModule\BTMemoryModule.pas',
  Concepts.BTMemoryModule.Form in 'Forms\Concepts.BTMemoryModule.Form.pas' {frmBTMemoryModule},
  {$ENDIF }
  {$IFDEF CHROMETABS}
  ChromeTabs in 'Libraries\TChromeTabs\Lib\ChromeTabs.pas',
  ChromeTabsClasses in 'Libraries\TChromeTabs\Lib\ChromeTabsClasses.pas',
  ChromeTabsControls in 'Libraries\TChromeTabs\Lib\ChromeTabsControls.pas',
  ChromeTabsGlassForm in 'Libraries\TChromeTabs\Lib\ChromeTabsGlassForm.pas',
  ChromeTabsLog in 'Libraries\TChromeTabs\Lib\ChromeTabsLog.pas',
  ChromeTabsThreadTimer in 'Libraries\TChromeTabs\Lib\ChromeTabsThreadTimer.pas',
  ChromeTabsTypes in 'Libraries\TChromeTabs\Lib\ChromeTabsTypes.pas',
  ChromeTabsUtils in 'Libraries\TChromeTabs\Lib\ChromeTabsUtils.pas',
  Concepts.ChromeTabs.Form in 'Forms\Concepts.ChromeTabs.Form.pas' {frmChromeTabs},
  {$ENDIF }
  {$IFDEF DEVEXPRESS}
  Concepts.DevExpress.cxEditors.Form in 'Forms\Concepts.DevExpress.cxEditors.Form.pas',
  {$ENDIF }
  Concepts.DSharp.Bindings.Form in 'Forms\Concepts.DSharp.Bindings.Form.pas' {frmBindings},
  Concepts.DSharp.TreeViewPresenter.Tree.Form in 'Forms\Concepts.DSharp.TreeViewPresenter.Tree.Form.pas' {frmTreeViewPresenterTree},
  Concepts.Factories in 'Concepts.Factories.pas',
  Concepts.MainForm in 'Concepts.MainForm.pas' {frmMain},
  Concepts.Manager in 'Concepts.Manager.pas',
  Concepts.Registration in 'Concepts.Registration.pas',
  Concepts.Resources in 'Concepts.Resources.pas' {dmResources: TDataModule},
  Concepts.RTTEye.Form in 'Forms\Concepts.RTTEye.Form.pas' {frmRTTEye},
  Concepts.RTTEye.Templates in 'Types\Concepts.RTTEye.Templates.pas',
  Concepts.Spring.Collections.Form in 'Forms\Concepts.Spring.Collections.Form.pas' {frmCollections},
  Concepts.Spring.Interception.Form in 'Forms\Concepts.Spring.Interception.Form.pas' {frmSpringInterception},
  Concepts.Spring.LazyInstantiation.Form in 'Forms\Concepts.Spring.LazyInstantiation.Form.pas' {frmLazyInstantiation},
  Concepts.Spring.Logging.Form in 'Forms\Concepts.Spring.Logging.Form.pas' {frmSpringLogging},
  Concepts.Spring.MultiCastEvents.ChildForm in 'Forms\Concepts.Spring.MultiCastEvents.ChildForm.pas' {frmMulticastEventsChild},
  Concepts.Spring.MultiCastEvents.Data in 'Forms\Concepts.Spring.MultiCastEvents.Data.pas',
  Concepts.Spring.MultiCastEvents.Form in 'Forms\Concepts.Spring.MultiCastEvents.Form.pas' {frmMulticastEvents},
  Concepts.Spring.ObjectDataSet.Form in 'Forms\Concepts.Spring.ObjectDataSet.Form.pas' {frmObjectDataSet},
  Concepts.Spring.Types.Form in 'Forms\Concepts.Spring.Types.Form.pas' {frmSpringTypes},
  Concepts.Spring.Utils.Form in 'Forms\Concepts.Spring.Utils.Form.pas' {frmSpringUtils},
  Concepts.System.AnonymousMethods.Form in 'Forms\Concepts.System.AnonymousMethods.Form.pas' {frmAnonymousMethods},
  Concepts.System.InterfaceImplementationByAggregation.Form in 'Forms\Concepts.System.InterfaceImplementationByAggregation.Form.pas' {frmIterFaceImplementationByAggregation},
  Concepts.System.Libraries.Form in 'Forms\Concepts.System.Libraries.Form.pas' {frmLibraries},
  Concepts.System.LiveBindings.Form in 'Forms\Concepts.System.LiveBindings.Form.pas' {frmLiveBindings},
  Concepts.System.RegularExpressions.Form in 'Forms\Concepts.System.RegularExpressions.Form.pas' {frmRegularExpressions},
  Concepts.System.RTTI.Form in 'Forms\Concepts.System.RTTI.Form.pas' {frmRTTI},
  Concepts.System.Threading.Form in 'Forms\Concepts.System.Threading.Form.pas' {frmThreading},
  Concepts.System.Threads.Form in 'Forms\Concepts.System.Threads.Form.pas' {frmThreads},
  Concepts.System.Variants.Form in 'Forms\Concepts.System.Variants.Form.pas' {frmVariants},
  Concepts.System.VirtualInterface.Form in 'Forms\Concepts.System.VirtualInterface.Form.pas' {frmVirtualInterfaceDemo},
  Concepts.System.VirtualMethodInterceptor.Form in 'Forms\Concepts.System.VirtualMethodInterceptor.Form.pas' {frmVirtualMethodInterceptor},
  Concepts.Types.Contact in 'Types\Concepts.Types.Contact.pas',
  Concepts.Types.ValidationRules in 'Types\Concepts.Types.ValidationRules.pas',
  Concepts.Utils in 'Concepts.Utils.pas',
  Concepts.Vcl.GridPanel.Form in 'Forms\Concepts.Vcl.GridPanel.Form.pas' {frmGridPanel},
  {$IFDEF DELPHIX_SEATTLE_UP}
  Concepts.Vcl.RelativePanel.Form in 'Forms\Concepts.Vcl.RelativePanel.Form.pas' {frmRelativePanel},
  {$ENDIF }
  Concepts.WinApi.LockPaint.Form in 'Forms\Concepts.WinApi.LockPaint.Form.pas' {frmLockPaint},
  DDuce.Components.DBGridView in 'Libraries\DDuce\Components\DDuce.Components.DBGridView.pas',
  DDuce.Components.GridView in 'Libraries\DDuce\Components\DDuce.Components.GridView.pas',
  DDuce.Components.Inspector in 'Libraries\DDuce\Components\DDuce.Components.Inspector.pas',
  DDuce.Components.LogTree in 'Libraries\DDuce\Components\DDuce.Components.LogTree.pas',
  DDuce.Components.PropertyInspector in 'Libraries\DDuce\Components\DDuce.Components.PropertyInspector.pas',
  DDuce.Components.PropertyInspector.CollectionEditor in 'Libraries\DDuce\Components\DDuce.Components.PropertyInspector.CollectionEditor.pas' {frmCollectionEditor},
  DDuce.Components.PropertyInspector.StringsEditor in 'Libraries\DDuce\Components\DDuce.Components.PropertyInspector.StringsEditor.pas' {StringsEditorDialog},
  DDuce.Components.XMLTree in 'Libraries\DDuce\Components\DDuce.Components.XMLTree.pas',
  DDuce.Components.XMLTree.Editors in 'Libraries\DDuce\Components\DDuce.Components.XMLTree.Editors.pas',
  DDuce.Components.XMLTree.NodeAttributes in 'Libraries\DDuce\Components\DDuce.Components.XMLTree.NodeAttributes.pas',
  DDuce.DynamicRecord in 'Libraries\DDuce\DDuce.DynamicRecord.pas',
  DDuce.RandomData in 'Libraries\DDuce\DDuce.RandomData.pas',
  DDuce.Reflect in 'Libraries\DDuce\DDuce.Reflect.pas',
  DDuce.ScopedReference in 'Libraries\DDuce\DDuce.ScopedReference.pas',
  DSharp.Bindings in 'Libraries\DSharp\DSharp.Bindings.pas',
  DSharp.Bindings.Collections in 'Libraries\DSharp\DSharp.Bindings.Collections.pas',
  DSharp.Bindings.CollectionView in 'Libraries\DSharp\DSharp.Bindings.CollectionView.pas',
  DSharp.Bindings.CollectionView.Adapters in 'Libraries\DSharp\DSharp.Bindings.CollectionView.Adapters.pas',
  DSharp.Bindings.CollectionView.VCLAdapters in 'Libraries\DSharp\DSharp.Bindings.CollectionView.VCLAdapters.pas',
  DSharp.Bindings.Exceptions in 'Libraries\DSharp\DSharp.Bindings.Exceptions.pas',
  DSharp.Bindings.Notifications in 'Libraries\DSharp\DSharp.Bindings.Notifications.pas',
  DSharp.Bindings.Validations in 'Libraries\DSharp\DSharp.Bindings.Validations.pas',
  DSharp.Bindings.VCLControls in 'Libraries\DSharp\DSharp.Bindings.VCLControls.pas',
  DSharp.Bindings.VCLControls.Extensions in 'Libraries\DSharp\DSharp.Bindings.VCLControls.Extensions.pas',
  DSharp.Collections.ObservableCollection in 'Libraries\DSharp\DSharp.Collections.ObservableCollection.pas',
  DSharp.ComponentModel.DataAnnotations in 'Libraries\DSharp\DSharp.ComponentModel.DataAnnotations.pas',
  DSharp.Core.Collections in 'Libraries\DSharp\DSharp.Core.Collections.pas',
  DSharp.Core.CopyOperator in 'Libraries\DSharp\DSharp.Core.CopyOperator.pas',
  DSharp.Core.DataConversion in 'Libraries\DSharp\DSharp.Core.DataConversion.pas',
  DSharp.Core.DataTemplates in 'Libraries\DSharp\DSharp.Core.DataTemplates.pas',
  DSharp.Core.DataTemplates.Default in 'Libraries\DSharp\DSharp.Core.DataTemplates.Default.pas',
  DSharp.Core.DependencyProperty in 'Libraries\DSharp\DSharp.Core.DependencyProperty.pas',
  DSharp.Core.Editable in 'Libraries\DSharp\DSharp.Core.Editable.pas',
  DSharp.Core.Expressions in 'Libraries\DSharp\DSharp.Core.Expressions.pas',
  DSharp.Core.Framework in 'Libraries\DSharp\DSharp.Core.Framework.pas',
  DSharp.Core.Properties in 'Libraries\DSharp\DSharp.Core.Properties.pas',
  DSharp.Core.PropertyChangedBase in 'Libraries\DSharp\DSharp.Core.PropertyChangedBase.pas',
  DSharp.Core.Reflection in 'Libraries\DSharp\DSharp.Core.Reflection.pas',
  DSharp.Core.Utils in 'Libraries\DSharp\DSharp.Core.Utils.pas',
  DSharp.Core.Validations in 'Libraries\DSharp\DSharp.Core.Validations.pas',
  DSharp.Windows.ColumnDefinitions in 'Libraries\DSharp\DSharp.Windows.ColumnDefinitions.pas',
  DSharp.Windows.ColumnDefinitions.ControlTemplate in 'Libraries\DSharp\DSharp.Windows.ColumnDefinitions.ControlTemplate.pas',
  DSharp.Windows.ColumnDefinitions.RttiDataTemplate in 'Libraries\DSharp\DSharp.Windows.ColumnDefinitions.RttiDataTemplate.pas',
  DSharp.Windows.ControlTemplates in 'Libraries\DSharp\DSharp.Windows.ControlTemplates.pas',
  DSharp.Windows.CustomPresenter in 'Libraries\DSharp\DSharp.Windows.CustomPresenter.pas',
  DSharp.Windows.CustomPresenter.Types in 'Libraries\DSharp\DSharp.Windows.CustomPresenter.Types.pas',
  DSharp.Windows.TreeViewPresenter in 'Libraries\DSharp\DSharp.Windows.TreeViewPresenter.pas',
  {$IFDEF SQLBUILDER4D}
  Concepts.SQLBuilder4D.Form in 'Forms\Concepts.SQLBuilder4D.Form.pas' {frmSQLBuilder4D},
  SQLBuilder4D in 'Libraries\SQLBuilder4Delphi\src\SQLBuilder4D.pas',
  SQLBuilder4D.Parser in 'Libraries\SQLBuilder4Delphi\src\SQLBuilder4D.Parser.pas',
  SQLBuilder4D.Parser.GaSQLParser in 'Libraries\SQLBuilder4Delphi\src\SQLBuilder4D.Parser.GaSQLParser.pas',
  gaAdvancedSQLParser in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaAdvancedSQLParser.pas',
  gaBasicSQLParser in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaBasicSQLParser.pas',
  gaDeleteStm in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaDeleteStm.pas',
  gaInsertStm in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaInsertStm.pas',
  gaLnkList in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaLnkList.pas',
  gaParserVisitor in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaParserVisitor.pas',
  gaQueryParsersReg in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaQueryParsersReg.pas',
  gaSelectStm in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSelectStm.pas',
  gaSQLExpressionParsers in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLExpressionParsers.pas',
  gaSQLFieldRefParsers in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLFieldRefParsers.pas',
  gaSQLParserConsts in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLParserConsts.pas',
  gaSQLParserHelperClasses in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLParserHelperClasses.pas',
  gaSQLSelectFieldParsers in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLSelectFieldParsers.pas',
  gaSQLTableRefParsers in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLTableRefParsers.pas',
  gaUpdateStm in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaUpdateStm.pas',
  {$ENDIF }
  Spring in 'Libraries\Spring4D\Source\Base\Spring.pas',
  Spring.Collections in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.pas',
  Spring.Collections.Adapters in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Adapters.pas',
  Spring.Collections.Base in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Base.pas',
  Spring.Collections.Dictionaries in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Dictionaries.pas',
  Spring.Collections.Enumerable in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Enumerable.pas',
  Spring.Collections.Events in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Events.pas',
  Spring.Collections.Extensions in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Extensions.pas',
  Spring.Collections.LinkedLists in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.LinkedLists.pas',
  Spring.Collections.Lists in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Lists.pas',
  Spring.Collections.MultiMaps in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.MultiMaps.pas',
  Spring.Collections.Queues in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Queues.pas',
  Spring.Collections.Sets in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Sets.pas',
  Spring.Collections.Stacks in 'Libraries\Spring4D\Source\Base\Collections\Spring.Collections.Stacks.pas',
  Spring.Container in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.pas',
  Spring.Container.ActivatorExtension in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.ActivatorExtension.pas',
  Spring.Container.AutoMockExtension in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.AutoMockExtension.pas',
  Spring.Container.Builder in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.Builder.pas',
  Spring.Container.Common in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.Common.pas',
  Spring.Container.ComponentActivator in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.ComponentActivator.pas',
  Spring.Container.Core in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.Core.pas',
  Spring.Container.CreationContext in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.CreationContext.pas',
  Spring.Container.Extensions in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.Extensions.pas',
  Spring.Container.Injection in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.Injection.pas',
  Spring.Container.LifetimeManager in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.LifetimeManager.pas',
  Spring.Container.Pool in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.Pool.pas',
  Spring.Container.ProxyFactory in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.ProxyFactory.pas',
  Spring.Container.Registration in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.Registration.pas',
  Spring.Container.Resolvers in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.Resolvers.pas',
  Spring.Container.ResourceStrings in 'Libraries\Spring4D\Source\Core\Container\Spring.Container.ResourceStrings.pas',
  Spring.Cryptography in 'Libraries\Spring4D\Source\Extensions\Cryptography\Spring.Cryptography.pas',
  Spring.Cryptography.Base in 'Libraries\Spring4D\Source\Extensions\Cryptography\Spring.Cryptography.Base.pas',
  Spring.Cryptography.CRC in 'Libraries\Spring4D\Source\Extensions\Cryptography\Spring.Cryptography.CRC.pas',
  Spring.Cryptography.DES in 'Libraries\Spring4D\Source\Extensions\Cryptography\Spring.Cryptography.DES.pas',
  Spring.Cryptography.MD5 in 'Libraries\Spring4D\Source\Extensions\Cryptography\Spring.Cryptography.MD5.pas',
  Spring.Cryptography.SHA in 'Libraries\Spring4D\Source\Extensions\Cryptography\Spring.Cryptography.SHA.pas',
  Spring.Cryptography.Utils in 'Libraries\Spring4D\Source\Extensions\Cryptography\Spring.Cryptography.Utils.pas',
  Spring.DesignPatterns in 'Libraries\Spring4D\Source\Base\Spring.DesignPatterns.pas',
  Spring.Events in 'Libraries\Spring4D\Source\Base\Spring.Events.pas',
  Spring.Events.Base in 'Libraries\Spring4D\Source\Base\Spring.Events.Base.pas',
  Spring.Helpers in 'Libraries\Spring4D\Source\Base\Spring.Helpers.pas',
  Spring.Interception in 'Libraries\Spring4D\Source\Core\Interception\Spring.Interception.pas',
  Spring.Interception.AbstractInvocation in 'Libraries\Spring4D\Source\Core\Interception\Spring.Interception.AbstractInvocation.pas',
  Spring.Interception.ClassProxy in 'Libraries\Spring4D\Source\Core\Interception\Spring.Interception.ClassProxy.pas',
  Spring.Interception.CustomProxy in 'Libraries\Spring4D\Source\Core\Interception\Spring.Interception.CustomProxy.pas',
  Spring.Interception.InterfaceProxy in 'Libraries\Spring4D\Source\Core\Interception\Spring.Interception.InterfaceProxy.pas',
  Spring.Interception.ResourceStrings in 'Libraries\Spring4D\Source\Core\Interception\Spring.Interception.ResourceStrings.pas',
  Spring.Logging in 'Libraries\Spring4D\Source\Base\Logging\Spring.Logging.pas',
  Spring.Logging.Appenders in 'Libraries\Spring4D\Source\Base\Logging\Spring.Logging.Appenders.pas',
  Spring.Logging.Appenders.Base in 'Libraries\Spring4D\Source\Base\Logging\Spring.Logging.Appenders.Base.pas',
  Spring.Logging.Configuration in 'Libraries\Spring4D\Source\Core\Logging\Spring.Logging.Configuration.pas',
  Spring.Logging.Configuration.Builder in 'Libraries\Spring4D\Source\Core\Logging\Spring.Logging.Configuration.Builder.pas',
  Spring.Logging.Container in 'Libraries\Spring4D\Source\Core\Logging\Spring.Logging.Container.pas',
  Spring.Logging.Controller in 'Libraries\Spring4D\Source\Base\Logging\Spring.Logging.Controller.pas',
  Spring.Logging.Extensions in 'Libraries\Spring4D\Source\Base\Logging\Spring.Logging.Extensions.pas',
  Spring.Logging.Loggers in 'Libraries\Spring4D\Source\Base\Logging\Spring.Logging.Loggers.pas',
  Spring.Logging.NullLogger in 'Libraries\Spring4D\Source\Base\Logging\Spring.Logging.NullLogger.pas',
  Spring.Logging.ResourceStrings in 'Libraries\Spring4D\Source\Base\Logging\Spring.Logging.ResourceStrings.pas',
  Spring.Logging.Serializers in 'Libraries\Spring4D\Source\Base\Logging\Spring.Logging.Serializers.pas',
  Spring.MethodIntercept in 'Libraries\Spring4D\Source\Base\Spring.MethodIntercept.pas',
  Spring.Mocking in 'Libraries\Spring4D\Source\Core\Mocking\Spring.Mocking.pas',
  Spring.Mocking.Core in 'Libraries\Spring4D\Source\Core\Mocking\Spring.Mocking.Core.pas',
  Spring.Mocking.Interceptor in 'Libraries\Spring4D\Source\Core\Mocking\Spring.Mocking.Interceptor.pas',
  Spring.Patches.GetInvokeInfo in 'Libraries\Spring4D\Source\Base\Patches\Spring.Patches.GetInvokeInfo.pas',
  Spring.Patches.QC107219 in 'Libraries\Spring4D\Source\Base\Patches\Spring.Patches.QC107219.pas',
  Spring.Patches.QC93646 in 'Libraries\Spring4D\Source\Base\Patches\Spring.Patches.QC93646.pas',
  Spring.Patches.QC98671 in 'Libraries\Spring4D\Source\Base\Patches\Spring.Patches.QC98671.pas',
  Spring.Persistence.Adapters.ADO in 'Libraries\Spring4D\Source\Persistence\Adapters\Spring.Persistence.Adapters.ADO.pas',
  Spring.Persistence.Adapters.ASA in 'Libraries\Spring4D\Source\Persistence\Adapters\Spring.Persistence.Adapters.ASA.pas',
  Spring.Persistence.Adapters.DBX in 'Libraries\Spring4D\Source\Persistence\Adapters\Spring.Persistence.Adapters.DBX.pas',
  Spring.Persistence.Adapters.FieldCache in 'Libraries\Spring4D\Source\Persistence\Adapters\Spring.Persistence.Adapters.FieldCache.pas',
  Spring.Persistence.Adapters.FireDAC in 'Libraries\Spring4D\Source\Persistence\Adapters\Spring.Persistence.Adapters.FireDAC.pas',
  Spring.Persistence.Adapters.MSSQL in 'Libraries\Spring4D\Source\Persistence\Adapters\Spring.Persistence.Adapters.MSSQL.pas',
  Spring.Persistence.Adapters.Oracle in 'Libraries\Spring4D\Source\Persistence\Adapters\Spring.Persistence.Adapters.Oracle.pas',
  Spring.Persistence.Core.AbstractSession in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.AbstractSession.pas',
  Spring.Persistence.Core.Base in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.Base.pas',
  Spring.Persistence.Core.ConnectionFactory in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.ConnectionFactory.pas',
  Spring.Persistence.Core.DatabaseManager in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.DatabaseManager.pas',
  Spring.Persistence.Core.DetachedSession in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.DetachedSession.pas',
  Spring.Persistence.Core.EmbeddedEntity in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.EmbeddedEntity.pas',
  Spring.Persistence.Core.EntityCache in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.EntityCache.pas',
  Spring.Persistence.Core.EntityMap in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.EntityMap.pas',
  Spring.Persistence.Core.EntityWrapper in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.EntityWrapper.pas',
  Spring.Persistence.Core.Exceptions in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.Exceptions.pas',
  Spring.Persistence.Core.Graphics in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.Graphics.pas',
  Spring.Persistence.Core.Interfaces in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.Interfaces.pas',
  Spring.Persistence.Core.ListSession in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.ListSession.pas',
  Spring.Persistence.Core.Repository.Proxy in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.Repository.Proxy.pas',
  Spring.Persistence.Core.Repository.Simple in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.Repository.Simple.pas',
  Spring.Persistence.Core.ResourceStrings in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.ResourceStrings.pas',
  Spring.Persistence.Core.Session in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.Session.pas',
  Spring.Persistence.Core.ValueConverters in 'Libraries\Spring4D\Source\Persistence\Core\Spring.Persistence.Core.ValueConverters.pas',
  Spring.Persistence.Criteria in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.pas',
  Spring.Persistence.Criteria.Criterion.Abstract in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.Abstract.pas',
  Spring.Persistence.Criteria.Criterion.BetweenExpression in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.BetweenExpression.pas',
  Spring.Persistence.Criteria.Criterion.Conjunction in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.Conjunction.pas',
  Spring.Persistence.Criteria.Criterion.Disjunction in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.Disjunction.pas',
  Spring.Persistence.Criteria.Criterion.InExpression in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.InExpression.pas',
  Spring.Persistence.Criteria.Criterion.Junction in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.Junction.pas',
  Spring.Persistence.Criteria.Criterion.LikeExpression in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.LikeExpression.pas',
  Spring.Persistence.Criteria.Criterion.LogicalExpression in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.LogicalExpression.pas',
  Spring.Persistence.Criteria.Criterion.NullExpression in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.NullExpression.pas',
  Spring.Persistence.Criteria.Criterion.PropertyExpression in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.PropertyExpression.pas',
  Spring.Persistence.Criteria.Criterion.SimpleExpression in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Criterion.SimpleExpression.pas',
  Spring.Persistence.Criteria.Interfaces in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Interfaces.pas',
  Spring.Persistence.Criteria.OrderBy in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.OrderBy.pas',
  Spring.Persistence.Criteria.Properties in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Properties.pas',
  Spring.Persistence.Criteria.Restrictions in 'Libraries\Spring4D\Source\Persistence\Criteria\Spring.Persistence.Criteria.Restrictions.pas',
  Spring.Persistence.Mapping.Attributes in 'Libraries\Spring4D\Source\Persistence\Mapping\Spring.Persistence.Mapping.Attributes.pas',
  Spring.Persistence.Mapping.CodeGenerator in 'Libraries\Spring4D\Source\Persistence\Mapping\Spring.Persistence.Mapping.CodeGenerator.pas',
  Spring.Persistence.Mapping.CodeGenerator.Abstract in 'Libraries\Spring4D\Source\Persistence\Mapping\Spring.Persistence.Mapping.CodeGenerator.Abstract.pas',
  Spring.Persistence.Mapping.CodeGenerator.DB in 'Libraries\Spring4D\Source\Persistence\Mapping\Spring.Persistence.Mapping.CodeGenerator.DB.pas',
  Spring.Persistence.ObjectDataset in 'Libraries\Spring4D\Source\Persistence\ObjectDataset\Spring.Persistence.ObjectDataset.pas',
  Spring.Persistence.ObjectDataset.Abstract in 'Libraries\Spring4D\Source\Persistence\ObjectDataset\Spring.Persistence.ObjectDataset.Abstract.pas',
  Spring.Persistence.ObjectDataset.ActiveX in 'Libraries\Spring4D\Source\Persistence\ObjectDataset\Spring.Persistence.ObjectDataset.ActiveX.pas',
  Spring.Persistence.ObjectDataset.Algorithms.Sort in 'Libraries\Spring4D\Source\Persistence\ObjectDataset\Spring.Persistence.ObjectDataset.Algorithms.Sort.pas',
  Spring.Persistence.ObjectDataset.Blobs in 'Libraries\Spring4D\Source\Persistence\ObjectDataset\Spring.Persistence.ObjectDataset.Blobs.pas',
  Spring.Persistence.ObjectDataset.Designtime in 'Libraries\Spring4D\Source\Persistence\ObjectDataset\Spring.Persistence.ObjectDataset.Designtime.pas',
  Spring.Persistence.ObjectDataset.ExprParser in 'Libraries\Spring4D\Source\Persistence\ObjectDataset\Spring.Persistence.ObjectDataset.ExprParser.pas',
  Spring.Persistence.ObjectDataset.ExprParser.Functions in 'Libraries\Spring4D\Source\Persistence\ObjectDataset\Spring.Persistence.ObjectDataset.ExprParser.Functions.pas',
  Spring.Persistence.ObjectDataset.IndexList in 'Libraries\Spring4D\Source\Persistence\ObjectDataset\Spring.Persistence.ObjectDataset.IndexList.pas',
  Spring.Persistence.SQL.Commands in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.pas',
  Spring.Persistence.SQL.Commands.Abstract in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.Abstract.pas',
  Spring.Persistence.SQL.Commands.CreateForeignKey in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.CreateForeignKey.pas',
  Spring.Persistence.SQL.Commands.CreateSequence in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.CreateSequence.pas',
  Spring.Persistence.SQL.Commands.CreateTable in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.CreateTable.pas',
  Spring.Persistence.SQL.Commands.Delete in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.Delete.pas',
  Spring.Persistence.SQL.Commands.Insert in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.Insert.pas',
  Spring.Persistence.SQL.Commands.Page in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.Page.pas',
  Spring.Persistence.SQL.Commands.Select in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.Select.pas',
  Spring.Persistence.SQL.Commands.Update in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Commands.Update.pas',
  Spring.Persistence.SQL.Generators.Abstract in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.Abstract.pas',
  Spring.Persistence.SQL.Generators.Ansi in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.Ansi.pas',
  Spring.Persistence.SQL.Generators.ASA in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.ASA.pas',
  Spring.Persistence.SQL.Generators.Firebird in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.Firebird.pas',
  Spring.Persistence.SQL.Generators.MSSQL in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.MSSQL.pas',
  Spring.Persistence.SQL.Generators.MySQL in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.MySQL.pas',
  Spring.Persistence.SQL.Generators.NoSQL in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.NoSQL.pas',
  Spring.Persistence.SQL.Generators.Oracle in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.Oracle.pas',
  Spring.Persistence.SQL.Generators.PostgreSQL in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.PostgreSQL.pas',
  Spring.Persistence.SQL.Generators.Register in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.Register.pas',
  Spring.Persistence.SQL.Generators.SQLite3 in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Generators.SQLite3.pas',
  Spring.Persistence.SQL.Interfaces in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Interfaces.pas',
  Spring.Persistence.SQL.Params in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Params.pas',
  Spring.Persistence.SQL.Register in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Register.pas',
  Spring.Persistence.SQL.Types in 'Libraries\Spring4D\Source\Persistence\SQL\Spring.Persistence.SQL.Types.pas',
  Spring.ResourceStrings in 'Libraries\Spring4D\Source\Base\Spring.ResourceStrings.pas',
  Spring.Services in 'Libraries\Spring4D\Source\Core\Services\Spring.Services.pas',
  Spring.Services.Logging in 'Libraries\Spring4D\Source\Core\Services\Spring.Services.Logging.pas',
  Spring.SystemUtils in 'Libraries\Spring4D\Source\Base\Spring.SystemUtils.pas',
  Spring.Times in 'Libraries\Spring4D\Source\Base\Spring.Times.pas',
  Spring.Utils in 'Libraries\Spring4D\Source\Extensions\Utils\Spring.Utils.pas',
  Spring.Utils.IO in 'Libraries\Spring4D\Source\Extensions\Utils\Spring.Utils.IO.pas',
  Spring.Utils.WinApi in 'Libraries\Spring4D\Source\Extensions\Utils\Spring.Utils.WinApi.pas',
  Spring.ValueConverters in 'Libraries\Spring4D\Source\Base\Spring.ValueConverters.pas',
  Spring.VirtualClass in 'Libraries\Spring4D\Source\Base\Spring.VirtualClass.pas',
  Spring.VirtualInterface in 'Libraries\Spring4D\Source\Base\Spring.VirtualInterface.pas',
  VirtualTrees in 'Libraries\VirtualTreeView\Source\VirtualTrees.pas',
  VirtualTrees.Actions in 'Libraries\VirtualTreeView\Source\VirtualTrees.Actions.pas',
  VirtualTrees.Classes in 'Libraries\VirtualTreeView\Source\VirtualTrees.Classes.pas',
  VirtualTrees.ClipBoard in 'Libraries\VirtualTreeView\Source\VirtualTrees.ClipBoard.pas',
  VirtualTrees.Export in 'Libraries\VirtualTreeView\Source\VirtualTrees.Export.pas',
  VirtualTrees.StyleHooks in 'Libraries\VirtualTreeView\Source\VirtualTrees.StyleHooks.pas',
  VirtualTrees.Utils in 'Libraries\VirtualTreeView\Source\VirtualTrees.Utils.pas',
  VirtualTrees.WorkerThread in 'Libraries\VirtualTreeView\Source\VirtualTrees.WorkerThread.pas',
  VTAccessibility in 'Libraries\VirtualTreeView\Source\VTAccessibility.pas',
  VTAccessibilityFactory in 'Libraries\VirtualTreeView\Source\VTAccessibilityFactory.pas',
  VTHeaderPopup in 'Libraries\VirtualTreeView\Source\VTHeaderPopup.pas',
  DDuce.Logging.Appenders.WinIPC in 'Libraries\DDuce\Logging\DDuce.Logging.Appenders.WinIPC.pas',
  DDuce.Logging.Appenders.LogTree in 'Libraries\DDuce\Logging\DDuce.Logging.Appenders.LogTree.pas',
  DDuce.Components.Factories in 'Libraries\DDuce\Components\DDuce.Components.Factories.pas',
  Concepts.RTTEye.Data in 'Types\Concepts.RTTEye.Data.pas',
  Spring.Reflection in 'Libraries\Spring4D\Source\Base\Spring.Reflection.pas',
  Spring.Mocking.Matching in 'Libraries\Spring4D\Source\Core\Mocking\Spring.Mocking.Matching.pas',
  Concepts.DSharp.TreeViewPresenter.List.Form in 'Forms\Concepts.DSharp.TreeViewPresenter.List.Form.pas' {frmTreeViewPresenterList},
  {$IFDEF BCEDITOR}
  BCEditor.Consts in 'Libraries\TBCEditor\Source\BCEditor.Consts.pas',
  BCEditor.Editor.ActiveLine in 'Libraries\TBCEditor\Source\BCEditor.Editor.ActiveLine.pas',
  BCEditor.Editor.Base in 'Libraries\TBCEditor\Source\BCEditor.Editor.Base.pas',
  BCEditor.Editor.Bookmarks in 'Libraries\TBCEditor\Source\BCEditor.Editor.Bookmarks.pas',
  BCEditor.Editor.Caret.NonBlinking.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.NonBlinking.Colors.pas',
  BCEditor.Editor.Caret.NonBlinking in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.NonBlinking.pas',
  BCEditor.Editor.Caret.Offsets in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.Offsets.pas',
  BCEditor.Editor.Caret in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.pas',
  BCEditor.Editor.Caret.Styles in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.Styles.pas',
  BCEditor.Editor.CodeFolding.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Colors.pas',
  BCEditor.Editor.CodeFolding.Hint.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Colors.pas',
  BCEditor.Editor.CodeFolding.Hint.Form in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Form.pas',
  BCEditor.Editor.CodeFolding.Hint in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.pas',
  BCEditor.Editor.CodeFolding in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.pas',
  BCEditor.Editor.CodeFolding.Ranges in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Ranges.pas',
  BCEditor.Editor.CodeFolding.Regions in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Regions.pas',
  BCEditor.Editor.CompletionProposal.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Colors.pas',
  BCEditor.Editor.CompletionProposal.Columns in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Columns.pas',
  BCEditor.Editor.CompletionProposal in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.pas',
  BCEditor.Editor.CompletionProposal.PopupWindow in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.PopupWindow.pas',
  BCEditor.Editor.CompletionProposal.Trigger in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Trigger.pas',
  BCEditor.Editor.DB in 'Libraries\TBCEditor\Source\BCEditor.Editor.DB.pas',
  BCEditor.Editor.Directories in 'Libraries\TBCEditor\Source\BCEditor.Editor.Directories.pas',
  BCEditor.Editor.Glyph in 'Libraries\TBCEditor\Source\BCEditor.Editor.Glyph.pas',
  BCEditor.Editor.InternalImage in 'Libraries\TBCEditor\Source\BCEditor.Editor.InternalImage.pas',
  BCEditor.Editor.KeyCommands in 'Libraries\TBCEditor\Source\BCEditor.Editor.KeyCommands.pas',
  BCEditor.Editor.LeftMargin.Bookmarks.Panel in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.Bookmarks.Panel.pas',
  BCEditor.Editor.LeftMargin.Bookmarks in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.Bookmarks.pas',
  BCEditor.Editor.LeftMargin.Border in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.Border.pas',
  BCEditor.Editor.LeftMargin.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.Colors.pas',
  BCEditor.Editor.LeftMargin.LineNumbers in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.LineNumbers.pas',
  BCEditor.Editor.LeftMargin.LineState in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.LineState.pas',
  BCEditor.Editor.LeftMargin in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.pas',
  BCEditor.Editor.LineSpacing in 'Libraries\TBCEditor\Source\BCEditor.Editor.LineSpacing.pas',
  BCEditor.Editor.MatchingPair.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.MatchingPair.Colors.pas',
  BCEditor.Editor.MatchingPair in 'Libraries\TBCEditor\Source\BCEditor.Editor.MatchingPair.pas',
  BCEditor.Editor.Minimap.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Minimap.Colors.pas',
  BCEditor.Editor.Minimap in 'Libraries\TBCEditor\Source\BCEditor.Editor.Minimap.pas',
  BCEditor.Editor.Minimap.Indicator in 'Libraries\TBCEditor\Source\BCEditor.Editor.Minimap.Indicator.pas',
  BCEditor.Editor in 'Libraries\TBCEditor\Source\BCEditor.Editor.pas',
  BCEditor.Editor.PopupWindow in 'Libraries\TBCEditor\Source\BCEditor.Editor.PopupWindow.pas',
  BCEditor.Editor.Replace in 'Libraries\TBCEditor\Source\BCEditor.Editor.Replace.pas',
  BCEditor.Editor.RightMargin.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.RightMargin.Colors.pas',
  BCEditor.Editor.RightMargin in 'Libraries\TBCEditor\Source\BCEditor.Editor.RightMargin.pas',
  BCEditor.Editor.Scroll.Hint in 'Libraries\TBCEditor\Source\BCEditor.Editor.Scroll.Hint.pas',
  BCEditor.Editor.Scroll in 'Libraries\TBCEditor\Source\BCEditor.Editor.Scroll.pas',
  BCEditor.Editor.Search.Highlighter.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.Highlighter.Colors.pas',
  BCEditor.Editor.Search.Highlighter in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.Highlighter.pas',
  BCEditor.Editor.Search.Map.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.Map.Colors.pas',
  BCEditor.Editor.Search.Map in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.Map.pas',
  BCEditor.Editor.Search in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.pas',
  BCEditor.Editor.Selection.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Selection.Colors.pas',
  BCEditor.Editor.Selection in 'Libraries\TBCEditor\Source\BCEditor.Editor.Selection.pas',
  BCEditor.Editor.SkipRegions in 'Libraries\TBCEditor\Source\BCEditor.Editor.SkipRegions.pas',
  BCEditor.Editor.SpecialChars.EndOfLine in 'Libraries\TBCEditor\Source\BCEditor.Editor.SpecialChars.EndOfLine.pas',
  BCEditor.Editor.SpecialChars in 'Libraries\TBCEditor\Source\BCEditor.Editor.SpecialChars.pas',
  BCEditor.Editor.SpecialChars.Selection in 'Libraries\TBCEditor\Source\BCEditor.Editor.SpecialChars.Selection.pas',
  BCEditor.Editor.Tabs in 'Libraries\TBCEditor\Source\BCEditor.Editor.Tabs.pas',
  BCEditor.Editor.Undo.Item in 'Libraries\TBCEditor\Source\BCEditor.Editor.Undo.Item.pas',
  BCEditor.Editor.Undo.List in 'Libraries\TBCEditor\Source\BCEditor.Editor.Undo.List.pas',
  BCEditor.Editor.Undo in 'Libraries\TBCEditor\Source\BCEditor.Editor.Undo.pas',
  BCEditor.Editor.Utils in 'Libraries\TBCEditor\Source\BCEditor.Editor.Utils.pas',
  BCEditor.Editor.WordWrap.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.WordWrap.Colors.pas',
  BCEditor.Editor.WordWrap in 'Libraries\TBCEditor\Source\BCEditor.Editor.WordWrap.pas',
  BCEditor.Encoding in 'Libraries\TBCEditor\Source\BCEditor.Encoding.pas',
  BCEditor.Highlighter.Attributes in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Attributes.pas',
  BCEditor.Highlighter.Colors in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Colors.pas',
  BCEditor.Highlighter.Info in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Info.pas',
  BCEditor.Highlighter in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.pas',
  BCEditor.Highlighter.Rules in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Rules.pas',
  BCEditor.Highlighter.Token in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Token.pas',
  BCEditor.Highlighter.Comments in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Comments.pas',
  BCEditor.JsonDataObjects in 'Libraries\TBCEditor\Source\BCEditor.JsonDataObjects.pas',
  BCEditor.KeyboardHandler in 'Libraries\TBCEditor\Source\BCEditor.KeyboardHandler.pas',
  BCEditor.Language in 'Libraries\TBCEditor\Source\BCEditor.Language.pas',
  BCEditor.Lines in 'Libraries\TBCEditor\Source\BCEditor.Lines.pas',
  BCEditor.MacroRecorder in 'Libraries\TBCEditor\Source\BCEditor.MacroRecorder.pas',
  BCEditor.Print.HeaderFooter in 'Libraries\TBCEditor\Source\BCEditor.Print.HeaderFooter.pas',
  BCEditor.Print.Margins in 'Libraries\TBCEditor\Source\BCEditor.Print.Margins.pas',
  BCEditor.Print in 'Libraries\TBCEditor\Source\BCEditor.Print.pas',
  BCEditor.Print.Preview in 'Libraries\TBCEditor\Source\BCEditor.Print.Preview.pas',
  BCEditor.Print.PrinterInfo in 'Libraries\TBCEditor\Source\BCEditor.Print.PrinterInfo.pas',
  BCEditor.Print.Types in 'Libraries\TBCEditor\Source\BCEditor.Print.Types.pas',
  BCEditor.Search in 'Libraries\TBCEditor\Source\BCEditor.Search.pas',
  BCEditor.Search.RegularExpressions in 'Libraries\TBCEditor\Source\BCEditor.Search.RegularExpressions.pas',
  BCEditor.Search.Wildcard in 'Libraries\TBCEditor\Source\BCEditor.Search.Wildcard.pas',
  BCEditor.StyleHooks in 'Libraries\TBCEditor\Source\BCEditor.StyleHooks.pas',
  BCEditor.TextDrawer in 'Libraries\TBCEditor\Source\BCEditor.TextDrawer.pas',
  BCEditor.Types in 'Libraries\TBCEditor\Source\BCEditor.Types.pas',
  BCEditor.Utils in 'Libraries\TBCEditor\Source\BCEditor.Utils.pas',
  BCEditor.Editor.Minimap.Shadow in 'Libraries\TBCEditor\Source\BCEditor.Editor.Minimap.Shadow.pas',
  BCEditor.Highlighter.Import.JSON in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Import.JSON.pas',
  BCEditor.Editor.SyncEdit in 'Libraries\TBCEditor\Source\BCEditor.Editor.SyncEdit.pas',
  BCEditor.Editor.SyncEdit.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.SyncEdit.Colors.pas',
  BCEditor.Export.HTML in 'Libraries\TBCEditor\Source\BCEditor.Export.HTML.pas',
  {$ENDIF }
  Concepts.BCEditor.Form in 'Forms\Concepts.BCEditor.Form.pas' {frmBCEditor},
  Concepts.RTTEye.RttiTemplates in 'Types\Concepts.RTTEye.RttiTemplates.pas',
  {$IFDEF DELPHIZMQ}
  Concepts.ZeroMQ.Form in 'Forms\Concepts.ZeroMQ.Form.pas',
  ZeroMQ.API in 'Libraries\ZeroMQ\ZeroMQ.API.pas',
  ZeroMQ in 'Libraries\ZeroMQ\ZeroMQ.pas',
  {$ENDIF }
  Concepts.Spring.ClassProxy.Form in 'Forms\Concepts.Spring.ClassProxy.Form.pas' {frmClassProxy},
  {$IFDEF DDETOURS}
  CPUID in 'Libraries\DDetours\CPUID.pas',
  DDetours in 'Libraries\DDetours\DDetours.pas',
  InstDecode in 'Libraries\DDetours\InstDecode.pas',
  {$ENDIF }
  Concepts.DDetours.Form in 'Forms\Concepts.DDetours.Form.pas' {frmDDetours},
  //{$IFDEF ZOBJECTINSPECTOR}
  zBase in 'Libraries\TzObjectInspector\zBase.pas',
  zCollectionEditor in 'Libraries\TzObjectInspector\zCollectionEditor.pas' {zCollectionEditorDialog},
  zCanvasStack in 'Libraries\TzObjectInspector\zCanvasStack.pas',
  zGraphicDialog in 'Libraries\TzObjectInspector\zGraphicDialog.pas' {GraphicDialog},
  zObjInspDialogs in 'Libraries\TzObjectInspector\zObjInspDialogs.pas',
  zObjInspector in 'Libraries\TzObjectInspector\zObjInspector.pas',
  zObjInspList in 'Libraries\TzObjectInspector\zObjInspList.pas',
  zRecList in 'Libraries\TzObjectInspector\zRecList.pas',
  zStringsDialog in 'Libraries\TzObjectInspector\zStringsDialog.pas' {StringsDialog},
  zUtils in 'Libraries\TzObjectInspector\zUtils.pas',
  Concepts.zObjectInspector.Form in 'Forms\Concepts.zObjectInspector.Form.pas' {frmzObjectInspector},
  Concepts.ComponentInspector in 'Concepts.ComponentInspector.pas' {frmComponentInspector},
  Concepts.Spring.Persistence.Form in 'Forms\Concepts.Spring.Persistence.Form.pas' {frmSpringPersistence},
  Concepts.Synapse.Serial.Form in 'Forms\Concepts.Synapse.Serial.Form.pas' {frmSynapseSerial},
  synaser in 'Libraries\synapse\synaser.pas',
  synafpc in 'Libraries\synapse\synafpc.pas',
  synautil in 'Libraries\synapse\synautil.pas',
  DDuce.WinIPC.Client in 'Libraries\DDuce\DDuce.WinIPC.Client.pas',
  DDuce.WinIPC.Server in 'Libraries\DDuce\DDuce.WinIPC.Server.pas',
  Concepts.ZeroMQ.Data in 'Forms\Concepts.ZeroMQ.Data.pas',
  DDuce.Logger.Base in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Base.pas',
  DDuce.Logger.Channels.Base in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.Base.pas',
  DDuce.Logger.Channels.LogFile in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.LogFile.pas',
  DDuce.Logger.Channels in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.pas',
  DDuce.Logger.Channels.WinIPC in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.WinIPC.pas',
  DDuce.Logger.Channels.WinODS in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.WinODS.pas',
  DDuce.Logger.Channels.ZeroMQ in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.ZeroMQ.pas',
  DDuce.Logger.Factories in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Factories.pas',
  DDuce.Logger.Interfaces in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Interfaces.pas',
  DDuce.Logger in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.pas';

{$R *.res}

begin
  {$WARNINGS OFF}
  ReportMemoryLeaksOnShutdown := DebugHook > 0;
  {$WARNINGS ON}
  Application.Initialize;
  TConcepts.RegisterConcepts;
  Application.CreateForm(TdmResources, dmResources);
  if ConceptManager.ItemList.Count = 1 then
  begin
    ConceptManager.Execute(ConceptManager.ItemList.First);
  end
  else
  begin
    Application.Title := 'Concepts';
    Application.CreateForm(TfrmMain, frmMain);
  end;
  Application.Run;

end.

