{
  Copyright (C) 2013-2018 Tim Sinaeve tim.sinaeve@gmail.com

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
}

{ By (un)commenting the following defines you can customize the project's
  dependencies. }

{$DEFINE BCEDITOR}      // TBCEditor control
{$DEFINE CHROMETABS}    // TChromeTabs control
{$DEFINE DDETOURS}      // DDetours unit
{$DEFINE DDUCE}         // DDuce - http://github.com/beNative/dduce
{$DEFINE DELPHIZMQ}     // DelphiZMQ wrapper
{$DEFINE DSHARP}        // DSharp - http://bitbucket.org/sglienke/dsharp
{$DEFINE FMXCONTAINER}  // TFireMonkeyContainer
{$DEFINE INDY}          // Indy
{$DEFINE SPRING}        // Spring4D - http://bitbucket.org/sglienke/spring4d
{$DEFINE SQLBUILDER4D}  // SQLBuilder4D.pas
{$DEFINE SYNAPSE}       // Synapse library
{$DEFINE SYNEDIT}       // SynEdit control
{$DEFINE SYSTEM}        // Delphi RTL units ('System' prefix)
{$DEFINE VCL}           // Delphi VCL units ('Vcl' prefix)
{$DEFINE VIRTUALTREES}  // Virtual Treeview - http://github.com/Virtual-TreeView/Virtual-TreeView
{$DEFINE WINAPI}        // Delphi WinApi units ('WinApi' prefix)
{$DEFINE ZOBJECTINSPECTOR} // TzObjectInspector
{$DEFINE DEVEXPRESS}    // DevExpress - http://www.devexpress.com/Products/VCL/
{.$DEFINE BTMEMORYMODULE} // BTMemoryModule.pas
{.$DEFINE FIREDAC}       // Delphi FireDAC units ('FireDAC' prefix)
{.$DEFINE FASTMM}         // FastMM
