program Concepts;

{$I Concepts.inc}

uses
  Vcl.Themes,
  Vcl.Styles,
  Vcl.Forms,
  BTMemoryModule in 'Libraries\BTMemoryModule\BTMemoryModule.pas',
  Concepts.BTMemoryModule.Form in 'Forms\Concepts.BTMemoryModule.Form.pas' {frmBTMemoryModule},
  ChromeTabs in 'Libraries\TChromeTabs\Lib\ChromeTabs.pas',
  ChromeTabsClasses in 'Libraries\TChromeTabs\Lib\ChromeTabsClasses.pas',
  ChromeTabsControls in 'Libraries\TChromeTabs\Lib\ChromeTabsControls.pas',
  ChromeTabsGlassForm in 'Libraries\TChromeTabs\Lib\ChromeTabsGlassForm.pas',
  ChromeTabsLog in 'Libraries\TChromeTabs\Lib\ChromeTabsLog.pas',
  ChromeTabsThreadTimer in 'Libraries\TChromeTabs\Lib\ChromeTabsThreadTimer.pas',
  ChromeTabsTypes in 'Libraries\TChromeTabs\Lib\ChromeTabsTypes.pas',
  ChromeTabsUtils in 'Libraries\TChromeTabs\Lib\ChromeTabsUtils.pas',
  Concepts.ChromeTabs.Form in 'Forms\Concepts.ChromeTabs.Form.pas' {frmChromeTabs},
  Concepts.DSharp.TreeViewPresenter.Tree.Form in 'Forms\Concepts.DSharp.TreeViewPresenter.Tree.Form.pas' {frmTreeViewPresenterTree},
  Concepts.Factories in 'Concepts.Factories.pas',
  Concepts.MainForm in 'Concepts.MainForm.pas' {frmMain},
  Concepts.Manager in 'Concepts.Manager.pas',
  Concepts.Registration in 'Concepts.Registration.pas',
  Concepts.Resources in 'Concepts.Resources.pas' {dmResources: TDataModule},
  Concepts.RTTEye.Form in 'Forms\Concepts.RTTEye.Form.pas' {frmRTTEye},
  Concepts.RTTEye.Templates in 'Types\Concepts.RTTEye.Templates.pas',
  Concepts.Spring.Collections.Form in 'Forms\Concepts.Spring.Collections.Form.pas' {frmCollections},
  Concepts.Spring.Interception.Form in 'Forms\Concepts.Spring.Interception.Form.pas' {frmSpringInterception},
  Concepts.Spring.LazyInstantiation.Form in 'Forms\Concepts.Spring.LazyInstantiation.Form.pas' {frmLazyInstantiation},
  Concepts.Spring.Logging.Form in 'Forms\Concepts.Spring.Logging.Form.pas' {frmSpringLogging},
  Concepts.Spring.MultiCastEvents.ChildForm in 'Forms\Concepts.Spring.MultiCastEvents.ChildForm.pas' {frmMulticastEventsChild},
  Concepts.Spring.MultiCastEvents.Data in 'Forms\Concepts.Spring.MultiCastEvents.Data.pas',
  Concepts.Spring.MultiCastEvents.Form in 'Forms\Concepts.Spring.MultiCastEvents.Form.pas' {frmMulticastEvents},
  Concepts.Spring.ObjectDataSet.Form in 'Forms\Concepts.Spring.ObjectDataSet.Form.pas' {frmObjectDataSet},
  Concepts.Spring.Types.Form in 'Forms\Concepts.Spring.Types.Form.pas' {frmSpringTypes},
  Concepts.Spring.Utils.Form in 'Forms\Concepts.Spring.Utils.Form.pas' {frmSpringUtils},
  Concepts.System.AnonymousMethods.Form in 'Forms\Concepts.System.AnonymousMethods.Form.pas' {frmAnonymousMethods},
  Concepts.System.InterfaceImplementationByAggregation.Form in 'Forms\Concepts.System.InterfaceImplementationByAggregation.Form.pas' {frmIterFaceImplementationByAggregation},
  Concepts.System.Libraries.Form in 'Forms\Concepts.System.Libraries.Form.pas' {frmLibraries},
  Concepts.System.LiveBindings.Form in 'Forms\Concepts.System.LiveBindings.Form.pas' {frmLiveBindings},
  Concepts.System.RegularExpressions.Form in 'Forms\Concepts.System.RegularExpressions.Form.pas' {frmRegularExpressions},
  Concepts.System.RTTI.Form in 'Forms\Concepts.System.RTTI.Form.pas' {frmRTTI},
  Concepts.System.Threading.Form in 'Forms\Concepts.System.Threading.Form.pas' {frmThreading},
  Concepts.System.Threads.Form in 'Forms\Concepts.System.Threads.Form.pas' {frmThreads},
  Concepts.System.Variants.Form in 'Forms\Concepts.System.Variants.Form.pas' {frmVariants},
  Concepts.System.VirtualInterface.Form in 'Forms\Concepts.System.VirtualInterface.Form.pas' {frmVirtualInterfaceDemo},
  Concepts.System.VirtualMethodInterceptor.Form in 'Forms\Concepts.System.VirtualMethodInterceptor.Form.pas' {frmVirtualMethodInterceptor},
  Concepts.Types.Contact in 'Types\Concepts.Types.Contact.pas',
  Concepts.Utils in 'Concepts.Utils.pas',
  Concepts.Vcl.GridPanel.Form in 'Forms\Concepts.Vcl.GridPanel.Form.pas' {frmGridPanel},
  Concepts.Indy.TCP.Form in 'Forms\Concepts.Indy.TCP.Form.pas' {frmIndyTCP},
  Concepts.Vcl.RelativePanel.Form in 'Forms\Concepts.Vcl.RelativePanel.Form.pas' {frmRelativePanel},
  Concepts.WinApi.LockPaint.Form in 'Forms\Concepts.WinApi.LockPaint.Form.pas' {frmLockPaint},
  DDuce.Components.DBGridView in 'Libraries\DDuce\Components\DDuce.Components.DBGridView.pas',
  DDuce.Components.GridView in 'Libraries\DDuce\Components\DDuce.Components.GridView.pas',
  DDuce.Components.Inspector in 'Libraries\DDuce\Components\DDuce.Components.Inspector.pas',
  DDuce.Components.LogTree in 'Libraries\DDuce\Components\DDuce.Components.LogTree.pas',
  DDuce.Components.PropertyInspector in 'Libraries\DDuce\Components\DDuce.Components.PropertyInspector.pas',
  DDuce.Components.PropertyInspector.CollectionEditor in 'Libraries\DDuce\Components\DDuce.Components.PropertyInspector.CollectionEditor.pas' {frmCollectionEditor},
  DDuce.Components.PropertyInspector.StringsEditor in 'Libraries\DDuce\Components\DDuce.Components.PropertyInspector.StringsEditor.pas' {StringsEditorDialog},
  DDuce.DynamicRecord in 'Libraries\DDuce\DDuce.DynamicRecord.pas',
  DDuce.RandomData in 'Libraries\DDuce\DDuce.RandomData.pas',
  DDuce.Reflect in 'Libraries\DDuce\DDuce.Reflect.pas',
  DDuce.ScopedReference in 'Libraries\DDuce\DDuce.ScopedReference.pas',
  DSharp.Bindings in 'Libraries\DSharp\DSharp.Bindings.pas',
  DSharp.Bindings.Collections in 'Libraries\DSharp\DSharp.Bindings.Collections.pas',
  DSharp.Bindings.CollectionView in 'Libraries\DSharp\DSharp.Bindings.CollectionView.pas',
  DSharp.Bindings.CollectionView.Adapters in 'Libraries\DSharp\DSharp.Bindings.CollectionView.Adapters.pas',
  DSharp.Bindings.CollectionView.VCLAdapters in 'Libraries\DSharp\DSharp.Bindings.CollectionView.VCLAdapters.pas',
  DSharp.Bindings.Exceptions in 'Libraries\DSharp\DSharp.Bindings.Exceptions.pas',
  DSharp.Bindings.Notifications in 'Libraries\DSharp\DSharp.Bindings.Notifications.pas',
  DSharp.Bindings.Validations in 'Libraries\DSharp\DSharp.Bindings.Validations.pas',
  DSharp.Bindings.VCLControls in 'Libraries\DSharp\DSharp.Bindings.VCLControls.pas',
  DSharp.Bindings.VCLControls.Extensions in 'Libraries\DSharp\DSharp.Bindings.VCLControls.Extensions.pas',
  DSharp.Collections.ObservableCollection in 'Libraries\DSharp\DSharp.Collections.ObservableCollection.pas',
  DSharp.ComponentModel.DataAnnotations in 'Libraries\DSharp\DSharp.ComponentModel.DataAnnotations.pas',
  DSharp.Core.Collections in 'Libraries\DSharp\DSharp.Core.Collections.pas',
  DSharp.Core.CopyOperator in 'Libraries\DSharp\DSharp.Core.CopyOperator.pas',
  DSharp.Core.DataConversion in 'Libraries\DSharp\DSharp.Core.DataConversion.pas',
  DSharp.Core.DataTemplates in 'Libraries\DSharp\DSharp.Core.DataTemplates.pas',
  DSharp.Core.DataTemplates.Default in 'Libraries\DSharp\DSharp.Core.DataTemplates.Default.pas',
  DSharp.Core.DependencyProperty in 'Libraries\DSharp\DSharp.Core.DependencyProperty.pas',
  DSharp.Core.Editable in 'Libraries\DSharp\DSharp.Core.Editable.pas',
  DSharp.Core.Expressions in 'Libraries\DSharp\DSharp.Core.Expressions.pas',
  DSharp.Core.Framework in 'Libraries\DSharp\DSharp.Core.Framework.pas',
  DSharp.Core.Properties in 'Libraries\DSharp\DSharp.Core.Properties.pas',
  DSharp.Core.PropertyChangedBase in 'Libraries\DSharp\DSharp.Core.PropertyChangedBase.pas',
  DSharp.Core.Reflection in 'Libraries\DSharp\DSharp.Core.Reflection.pas',
  DSharp.Core.Utils in 'Libraries\DSharp\DSharp.Core.Utils.pas',
  DSharp.Core.Validations in 'Libraries\DSharp\DSharp.Core.Validations.pas',
  DSharp.Windows.ColumnDefinitions in 'Libraries\DSharp\DSharp.Windows.ColumnDefinitions.pas',
  DSharp.Windows.ColumnDefinitions.ControlTemplate in 'Libraries\DSharp\DSharp.Windows.ColumnDefinitions.ControlTemplate.pas',
  DSharp.Windows.ColumnDefinitions.RttiDataTemplate in 'Libraries\DSharp\DSharp.Windows.ColumnDefinitions.RttiDataTemplate.pas',
  DSharp.Windows.ControlTemplates in 'Libraries\DSharp\DSharp.Windows.ControlTemplates.pas',
  DSharp.Windows.CustomPresenter in 'Libraries\DSharp\DSharp.Windows.CustomPresenter.pas',
  DSharp.Windows.CustomPresenter.Types in 'Libraries\DSharp\DSharp.Windows.CustomPresenter.Types.pas',
  DSharp.Windows.TreeViewPresenter in 'Libraries\DSharp\DSharp.Windows.TreeViewPresenter.pas',
  Concepts.SQLBuilder4D.Form in 'Forms\Concepts.SQLBuilder4D.Form.pas' {frmSQLBuilder4D},
  SQLBuilder4D in 'Libraries\SQLBuilder4Delphi\src\SQLBuilder4D.pas',
  SQLBuilder4D.Parser in 'Libraries\SQLBuilder4Delphi\src\SQLBuilder4D.Parser.pas',
  SQLBuilder4D.Parser.GaSQLParser in 'Libraries\SQLBuilder4Delphi\src\SQLBuilder4D.Parser.GaSQLParser.pas',
  gaAdvancedSQLParser in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaAdvancedSQLParser.pas',
  gaBasicSQLParser in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaBasicSQLParser.pas',
  gaDeleteStm in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaDeleteStm.pas',
  gaInsertStm in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaInsertStm.pas',
  gaLnkList in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaLnkList.pas',
  gaParserVisitor in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaParserVisitor.pas',
  gaQueryParsersReg in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaQueryParsersReg.pas',
  gaSelectStm in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSelectStm.pas',
  gaSQLExpressionParsers in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLExpressionParsers.pas',
  gaSQLFieldRefParsers in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLFieldRefParsers.pas',
  gaSQLParserConsts in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLParserConsts.pas',
  gaSQLParserHelperClasses in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLParserHelperClasses.pas',
  gaSQLSelectFieldParsers in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLSelectFieldParsers.pas',
  gaSQLTableRefParsers in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaSQLTableRefParsers.pas',
  gaUpdateStm in 'Libraries\SQLBuilder4Delphi\dependencies\gaSQLParser\src\gaUpdateStm.pas',
  VirtualTrees in 'Libraries\VirtualTreeView\Source\VirtualTrees.pas',
  VirtualTrees.Actions in 'Libraries\VirtualTreeView\Source\VirtualTrees.Actions.pas',
  VirtualTrees.Classes in 'Libraries\VirtualTreeView\Source\VirtualTrees.Classes.pas',
  VirtualTrees.ClipBoard in 'Libraries\VirtualTreeView\Source\VirtualTrees.ClipBoard.pas',
  VirtualTrees.Export in 'Libraries\VirtualTreeView\Source\VirtualTrees.Export.pas',
  VirtualTrees.StyleHooks in 'Libraries\VirtualTreeView\Source\VirtualTrees.StyleHooks.pas',
  VirtualTrees.Utils in 'Libraries\VirtualTreeView\Source\VirtualTrees.Utils.pas',
  VirtualTrees.WorkerThread in 'Libraries\VirtualTreeView\Source\VirtualTrees.WorkerThread.pas',
  VTAccessibility in 'Libraries\VirtualTreeView\Source\VTAccessibility.pas',
  VTAccessibilityFactory in 'Libraries\VirtualTreeView\Source\VTAccessibilityFactory.pas',
  VTHeaderPopup in 'Libraries\VirtualTreeView\Source\VTHeaderPopup.pas',
  DDuce.Logging.Appenders.WinIPC in 'Libraries\DDuce\Logging\DDuce.Logging.Appenders.WinIPC.pas',
  DDuce.Logging.Appenders.LogTree in 'Libraries\DDuce\Logging\DDuce.Logging.Appenders.LogTree.pas',
  DDuce.Components.Factories in 'Libraries\DDuce\Components\DDuce.Components.Factories.pas',
  Concepts.RTTEye.Data in 'Types\Concepts.RTTEye.Data.pas',
  Concepts.DSharp.TreeViewPresenter.List.Form in 'Forms\Concepts.DSharp.TreeViewPresenter.List.Form.pas' {frmTreeViewPresenterList},
  BCEditor.Consts in 'Libraries\TBCEditor\Source\BCEditor.Consts.pas',
  BCEditor.Editor.ActiveLine in 'Libraries\TBCEditor\Source\BCEditor.Editor.ActiveLine.pas',
  BCEditor.Editor.Base in 'Libraries\TBCEditor\Source\BCEditor.Editor.Base.pas',
  BCEditor.Editor.Caret.NonBlinking.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.NonBlinking.Colors.pas',
  BCEditor.Editor.Caret.NonBlinking in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.NonBlinking.pas',
  BCEditor.Editor.Caret.Offsets in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.Offsets.pas',
  BCEditor.Editor.Caret in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.pas',
  BCEditor.Editor.Caret.Styles in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.Styles.pas',
  BCEditor.Editor.CodeFolding.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Colors.pas',
  BCEditor.Editor.CodeFolding.Hint.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Colors.pas',
  BCEditor.Editor.CodeFolding.Hint.Form in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Form.pas',
  BCEditor.Editor.CodeFolding.Hint in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.pas',
  BCEditor.Editor.CodeFolding in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.pas',
  BCEditor.Editor.CodeFolding.Ranges in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Ranges.pas',
  BCEditor.Editor.CodeFolding.Regions in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Regions.pas',
  BCEditor.Editor.CompletionProposal.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Colors.pas',
  BCEditor.Editor.CompletionProposal.Columns in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Columns.pas',
  BCEditor.Editor.CompletionProposal in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.pas',
  BCEditor.Editor.CompletionProposal.PopupWindow in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.PopupWindow.pas',
  BCEditor.Editor.CompletionProposal.Trigger in 'Libraries\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Trigger.pas',
  BCEditor.Editor.DB in 'Libraries\TBCEditor\Source\BCEditor.Editor.DB.pas',
  BCEditor.Editor.Directories in 'Libraries\TBCEditor\Source\BCEditor.Editor.Directories.pas',
  BCEditor.Editor.Glyph in 'Libraries\TBCEditor\Source\BCEditor.Editor.Glyph.pas',
  BCEditor.Editor.InternalImage in 'Libraries\TBCEditor\Source\BCEditor.Editor.InternalImage.pas',
  BCEditor.Editor.KeyCommands in 'Libraries\TBCEditor\Source\BCEditor.Editor.KeyCommands.pas',
  BCEditor.Editor.LeftMargin.Bookmarks in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.Bookmarks.pas',
  BCEditor.Editor.LeftMargin.Border in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.Border.pas',
  BCEditor.Editor.LeftMargin.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.Colors.pas',
  BCEditor.Editor.LeftMargin.LineNumbers in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.LineNumbers.pas',
  BCEditor.Editor.LeftMargin.LineState in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.LineState.pas',
  BCEditor.Editor.LeftMargin in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.pas',
  BCEditor.Editor.MatchingPair.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.MatchingPair.Colors.pas',
  BCEditor.Editor.MatchingPair in 'Libraries\TBCEditor\Source\BCEditor.Editor.MatchingPair.pas',
  BCEditor.Editor.Minimap.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Minimap.Colors.pas',
  BCEditor.Editor.Minimap in 'Libraries\TBCEditor\Source\BCEditor.Editor.Minimap.pas',
  BCEditor.Editor.Minimap.Indicator in 'Libraries\TBCEditor\Source\BCEditor.Editor.Minimap.Indicator.pas',
  BCEditor.Editor in 'Libraries\TBCEditor\Source\BCEditor.Editor.pas',
  BCEditor.Editor.PopupWindow in 'Libraries\TBCEditor\Source\BCEditor.Editor.PopupWindow.pas',
  BCEditor.Editor.Replace in 'Libraries\TBCEditor\Source\BCEditor.Editor.Replace.pas',
  BCEditor.Editor.RightMargin.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.RightMargin.Colors.pas',
  BCEditor.Editor.RightMargin in 'Libraries\TBCEditor\Source\BCEditor.Editor.RightMargin.pas',
  BCEditor.Editor.Scroll.Hint in 'Libraries\TBCEditor\Source\BCEditor.Editor.Scroll.Hint.pas',
  BCEditor.Editor.Scroll in 'Libraries\TBCEditor\Source\BCEditor.Editor.Scroll.pas',
  BCEditor.Editor.Search.Highlighter.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.Highlighter.Colors.pas',
  BCEditor.Editor.Search.Highlighter in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.Highlighter.pas',
  BCEditor.Editor.Search.Map.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.Map.Colors.pas',
  BCEditor.Editor.Search.Map in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.Map.pas',
  BCEditor.Editor.Search in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.pas',
  BCEditor.Editor.Selection.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Selection.Colors.pas',
  BCEditor.Editor.Selection in 'Libraries\TBCEditor\Source\BCEditor.Editor.Selection.pas',
  BCEditor.Editor.SkipRegions in 'Libraries\TBCEditor\Source\BCEditor.Editor.SkipRegions.pas',
  BCEditor.Editor.SpecialChars.EndOfLine in 'Libraries\TBCEditor\Source\BCEditor.Editor.SpecialChars.EndOfLine.pas',
  BCEditor.Editor.SpecialChars in 'Libraries\TBCEditor\Source\BCEditor.Editor.SpecialChars.pas',
  BCEditor.Editor.SpecialChars.Selection in 'Libraries\TBCEditor\Source\BCEditor.Editor.SpecialChars.Selection.pas',
  BCEditor.Editor.Tabs in 'Libraries\TBCEditor\Source\BCEditor.Editor.Tabs.pas',
  BCEditor.Editor.Undo.Item in 'Libraries\TBCEditor\Source\BCEditor.Editor.Undo.Item.pas',
  BCEditor.Editor.Undo.List in 'Libraries\TBCEditor\Source\BCEditor.Editor.Undo.List.pas',
  BCEditor.Editor.Undo in 'Libraries\TBCEditor\Source\BCEditor.Editor.Undo.pas',
  BCEditor.Editor.Utils in 'Libraries\TBCEditor\Source\BCEditor.Editor.Utils.pas',
  BCEditor.Editor.WordWrap.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.WordWrap.Colors.pas',
  BCEditor.Editor.WordWrap in 'Libraries\TBCEditor\Source\BCEditor.Editor.WordWrap.pas',
  BCEditor.Encoding in 'Libraries\TBCEditor\Source\BCEditor.Encoding.pas',
  BCEditor.Highlighter.Attributes in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Attributes.pas',
  BCEditor.Highlighter.Colors in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Colors.pas',
  BCEditor.Highlighter.Info in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Info.pas',
  BCEditor.Highlighter in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.pas',
  BCEditor.Highlighter.Rules in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Rules.pas',
  BCEditor.Highlighter.Token in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Token.pas',
  BCEditor.Highlighter.Comments in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Comments.pas',
  BCEditor.JsonDataObjects in 'Libraries\TBCEditor\Source\BCEditor.JsonDataObjects.pas',
  BCEditor.KeyboardHandler in 'Libraries\TBCEditor\Source\BCEditor.KeyboardHandler.pas',
  BCEditor.Language in 'Libraries\TBCEditor\Source\BCEditor.Language.pas',
  BCEditor.Lines in 'Libraries\TBCEditor\Source\BCEditor.Lines.pas',
  BCEditor.MacroRecorder in 'Libraries\TBCEditor\Source\BCEditor.MacroRecorder.pas',
  BCEditor.Print.HeaderFooter in 'Libraries\TBCEditor\Source\BCEditor.Print.HeaderFooter.pas',
  BCEditor.Print.Margins in 'Libraries\TBCEditor\Source\BCEditor.Print.Margins.pas',
  BCEditor.Print in 'Libraries\TBCEditor\Source\BCEditor.Print.pas',
  BCEditor.Print.Preview in 'Libraries\TBCEditor\Source\BCEditor.Print.Preview.pas',
  BCEditor.Print.PrinterInfo in 'Libraries\TBCEditor\Source\BCEditor.Print.PrinterInfo.pas',
  BCEditor.Print.Types in 'Libraries\TBCEditor\Source\BCEditor.Print.Types.pas',
  BCEditor.Search in 'Libraries\TBCEditor\Source\BCEditor.Search.pas',
  BCEditor.Search.RegularExpressions in 'Libraries\TBCEditor\Source\BCEditor.Search.RegularExpressions.pas',
  BCEditor.Search.Wildcard in 'Libraries\TBCEditor\Source\BCEditor.Search.Wildcard.pas',
  BCEditor.StyleHooks in 'Libraries\TBCEditor\Source\BCEditor.StyleHooks.pas',
  BCEditor.Types in 'Libraries\TBCEditor\Source\BCEditor.Types.pas',
  BCEditor.Utils in 'Libraries\TBCEditor\Source\BCEditor.Utils.pas',
  BCEditor.Editor.Minimap.Shadow in 'Libraries\TBCEditor\Source\BCEditor.Editor.Minimap.Shadow.pas',
  BCEditor.Highlighter.Import.JSON in 'Libraries\TBCEditor\Source\BCEditor.Highlighter.Import.JSON.pas',
  BCEditor.Editor.SyncEdit in 'Libraries\TBCEditor\Source\BCEditor.Editor.SyncEdit.pas',
  BCEditor.Editor.SyncEdit.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.SyncEdit.Colors.pas',
  BCEditor.Export.HTML in 'Libraries\TBCEditor\Source\BCEditor.Export.HTML.pas',
  Concepts.BCEditor.Form in 'Forms\Concepts.BCEditor.Form.pas' {frmBCEditor},
  Concepts.RTTEye.RttiTemplates in 'Types\Concepts.RTTEye.RttiTemplates.pas',
  Concepts.ZeroMQ.Form in 'Forms\Concepts.ZeroMQ.Form.pas',
  ZeroMQ.API in 'Libraries\ZeroMQ\ZeroMQ.API.pas',
  ZeroMQ in 'Libraries\ZeroMQ\ZeroMQ.pas',
  Concepts.Spring.ClassProxy.Form in 'Forms\Concepts.Spring.ClassProxy.Form.pas' {frmClassProxy},
  CPUID in 'Libraries\DDetours\CPUID.pas',
  DDetours in 'Libraries\DDetours\DDetours.pas',
  InstDecode in 'Libraries\DDetours\InstDecode.pas',
  Concepts.DDetours.Form in 'Forms\Concepts.DDetours.Form.pas' {frmDDetours},
  Concepts.zObjectInspector.Form in 'Forms\Concepts.zObjectInspector.Form.pas' {frmzObjectInspector},
  Concepts.Spring.Persistence.Form in 'Forms\Concepts.Spring.Persistence.Form.pas' {frmSpringPersistence},
  Concepts.Synapse.Serial.Form in 'Forms\Concepts.Synapse.Serial.Form.pas' {frmSynapseSerial},
  synaser in 'Libraries\synapse\synaser.pas',
  synafpc in 'Libraries\synapse\synafpc.pas',
  synautil in 'Libraries\synapse\synautil.pas',
  DDuce.WinIPC.Client in 'Libraries\DDuce\DDuce.WinIPC.Client.pas',
  DDuce.WinIPC.Server in 'Libraries\DDuce\DDuce.WinIPC.Server.pas',
  Concepts.ZeroMQ.Data in 'Forms\Concepts.ZeroMQ.Data.pas',
  Concepts.Settings in 'Concepts.Settings.pas',
  DDuce.Logger.Base in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Base.pas',
  DDuce.Logger.Channels.Base in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.Base.pas',
  DDuce.Logger.Channels.LogFile in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.LogFile.pas',
  DDuce.Logger.Channels.WinIPC in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.WinIPC.pas',
  DDuce.Logger.Channels.WinODS in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.WinODS.pas',
  DDuce.Logger.Channels.ZeroMQ in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Channels.ZeroMQ.pas',
  DDuce.Logger.Factories in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Factories.pas',
  DDuce.Logger.Interfaces in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.Interfaces.pas',
  DDuce.Logger in 'Libraries\DDuce\Modules\Logger\DDuce.Logger.pas',
  Parnassus.FMXContainer in 'Libraries\firemonkey-container\Parnassus.FMXContainer.pas',
  Concepts.FMXContainer.Form in 'Forms\Concepts.FMXContainer.Form.pas' {frmFMXContainer},
  Concepts.FireMonkey.Form in 'Forms\Concepts.FireMonkey.Form.pas' {FireMonkeyForm},
  Concepts.System.StringList.Form in 'Forms\Concepts.System.StringList.Form.pas' {frmStringList},
  BCEditor.Editor.Marks in 'Libraries\TBCEditor\Source\BCEditor.Editor.Marks.pas',
  BCEditor.Editor.Caret.MultiEdit in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.MultiEdit.pas',
  BCEditor.Editor.Caret.MultiEdit.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.Caret.MultiEdit.Colors.pas',
  BCEditor.Editor.CodeFolding.Hint.Indicator in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Indicator.pas',
  BCEditor.Editor.CodeFolding.Hint.Indicator.Colors in 'Libraries\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Indicator.Colors.pas',
  BCEditor.Editor.LeftMargin.MarksPanel in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.MarksPanel.pas',
  BCEditor.Editor.LeftMargin.Marks in 'Libraries\TBCEditor\Source\BCEditor.Editor.LeftMargin.Marks.pas',
  BCEditor.Editor.Scroll.Shadow in 'Libraries\TBCEditor\Source\BCEditor.Editor.Scroll.Shadow.pas',
  BCEditor.Editor.Search.InSelection in 'Libraries\TBCEditor\Source\BCEditor.Editor.Search.InSelection.pas',
  BCEditor.Search.Normal in 'Libraries\TBCEditor\Source\BCEditor.Search.Normal.pas',
  BCEditor.PaintHelper in 'Libraries\TBCEditor\Source\BCEditor.PaintHelper.pas',
  BCEditor.Editor.UnknownChars in 'Libraries\TBCEditor\Source\BCEditor.Editor.UnknownChars.pas',
  DDuce.FormSettings in 'Libraries\DDuce\Modules\DDuce.FormSettings.pas',
  FloatConv.Double in 'Libraries\TzObjectInspector\FloatConv\FloatConv.Double.pas',
  FloatConv.Extended in 'Libraries\TzObjectInspector\FloatConv\FloatConv.Extended.pas',
  FloatConv in 'Libraries\TzObjectInspector\FloatConv\FloatConv.pas',
  FloatConv.Single in 'Libraries\TzObjectInspector\FloatConv\FloatConv.Single.pas',
  Concepts.zObjectInspector.ValueManager in 'Forms\Concepts.zObjectInspector.ValueManager.pas',
  ORM.Chinook.Album in 'ORM\ORM.Chinook.Album.pas',
  ORM.Chinook.Artist in 'ORM\ORM.Chinook.Artist.pas',
  ORM.Chinook.Customer in 'ORM\ORM.Chinook.Customer.pas',
  ORM.Chinook.Employee in 'ORM\ORM.Chinook.Employee.pas',
  ORM.Chinook.Genre in 'ORM\ORM.Chinook.Genre.pas',
  ORM.Chinook.Invoice in 'ORM\ORM.Chinook.Invoice.pas',
  ORM.Chinook.InvoiceLine in 'ORM\ORM.Chinook.InvoiceLine.pas',
  ORM.Chinook.MediaType in 'ORM\ORM.Chinook.MediaType.pas',
  ORM.Chinook.Playlist in 'ORM\ORM.Chinook.Playlist.pas',
  ORM.Chinook.PlaylistTrack in 'ORM\ORM.Chinook.PlaylistTrack.pas',
  ORM.Chinook.Track in 'ORM\ORM.Chinook.Track.pas',
  SQLite3 in 'Libraries\Spring4D\Marshmallow\External\SQLite3\SQLite3.pas',
  SQLiteTable3 in 'Libraries\Spring4D\Marshmallow\External\SQLite3\SQLiteTable3.pas',
  Concepts.zObjectInspector.StringsDialog.Form in 'Forms\Concepts.zObjectInspector.StringsDialog.Form.pas' {frmStringsDialog},
  zBase in 'Libraries\TzObjectInspector\zBase.pas',
  zCanvasStack in 'Libraries\TzObjectInspector\zCanvasStack.pas',
  zCollectionEditor in 'Libraries\TzObjectInspector\zCollectionEditor.pas' {zCollectionEditorDialog},
  zControlsReg in 'Libraries\TzObjectInspector\zControlsReg.pas',
  zGraphicDialog in 'Libraries\TzObjectInspector\zGraphicDialog.pas' {GraphicDialog},
  zObjInspDialogs in 'Libraries\TzObjectInspector\zObjInspDialogs.pas',
  zObjInspector in 'Libraries\TzObjectInspector\zObjInspector.pas',
  zObjInspList in 'Libraries\TzObjectInspector\zObjInspList.pas',
  zObjInspTypes in 'Libraries\TzObjectInspector\zObjInspTypes.pas',
  zRecList in 'Libraries\TzObjectInspector\zRecList.pas',
  zStringsDialog in 'Libraries\TzObjectInspector\zStringsDialog.pas' {StringsDialog},
  zUtils in 'Libraries\TzObjectInspector\zUtils.pas',
  zValueManager in 'Libraries\TzObjectInspector\zValueManager.pas',
  DDuce.Factories.VirtualTrees in 'Libraries\DDuce\Factories\DDuce.Factories.VirtualTrees.pas',
  DDuce.Factories.zObjInspector in 'Libraries\DDuce\Factories\DDuce.Factories.zObjInspector.pas',
  Concepts.SynEdit.Form in 'Forms\Concepts.SynEdit.Form.pas' {frmSynEdit},
  DSharp.DevExpress.GridViewPresenter in 'Libraries\DSharp\DSharp.DevExpress.GridViewPresenter.pas',
  DSharp.DevExpress.PresenterDataSource in 'Libraries\DSharp\DSharp.DevExpress.PresenterDataSource.pas',
  DSharp.DevExpress.TreeListPresenter in 'Libraries\DSharp\DSharp.DevExpress.TreeListPresenter.pas',
  Concepts.DevExpress.cxEditors.Form in 'Forms\Concepts.DevExpress.cxEditors.Form.pas' {frmcxEditors},
  Concepts.DevExpress.cxGridViewPresenter.Form in 'Forms\Concepts.DevExpress.cxGridViewPresenter.Form.pas' {frmcxGridViewPresenter},
  Concepts.VirtualTreeView.Form in 'Forms\Concepts.VirtualTreeView.Form.pas' {frmVirtualTreeView},
  Concepts.FireDAC.Form in 'Forms\Concepts.FireDAC.Form.pas' {frmFireDAC},
  Concepts.System.PublishedFields.Form in 'Forms\Concepts.System.PublishedFields.Form.pas' {frmPublishedFields},
  DDuce.ObjectInspector.zObjectInspector in 'Libraries\DDuce\Modules\ObjectInspector\DDuce.ObjectInspector.zObjectInspector.pas' {frmComponentInspectorzObjectInspector},
  DDuce.Factories.GridView in 'Libraries\DDuce\Factories\DDuce.Factories.GridView.pas';

{$R *.res}

{ Used to directly start a concept by name. If empty a list will be shown with
  all registered concepts. }
const
  EXECUTE_BY_NAME = '';
//  EXECUTE_BY_NAME = 'FireDAC';
  //EXECUTE_BY_NAME = 'ORM';
  //EXECUTE_BY_NAME = 'TStringList';
  //EXECUTE_BY_NAME = 'Indy';
  //EXECUTE_BY_NAME = 'Parallel Library';

begin
  {$WARNINGS OFF}
  ReportMemoryLeaksOnShutdown := DebugHook > 0;
  {$WARNINGS ON}
  Application.Initialize;
  TConcepts.RegisterConcepts;
  Logger.Channels.Add(TWinIPCChannel.Create);
  Application.CreateForm(TdmResources, dmResources);
  if not ConceptManager.Execute(EXECUTE_BY_NAME) then
  begin
    if ConceptManager.ItemList.Count = 1 then
    begin
      ConceptManager.Execute(ConceptManager.ItemList.Single);
    end
    else
    begin
      Application.Title := 'Concepts';
      Application.CreateForm(TfrmMain, frmMain);
    end;
  end;
  Application.Run;
end.


