object EditorView: TEditorView
  Left = 590
  Top = 268
  AlphaBlendValue = 128
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 421
  ClientWidth = 630
  Color = clWindow
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  ShowHint = True
  PixelsPerInch = 96
  TextHeight = 13
end
