unit Customers_Model;

interface

uses
  Mapping.Attributes, Core.Types, Graphics;

type
  [Entity]   
  [Table('Customers', '')]
  TCustomers = class
  private   
    FEMAIL: Nullable<string>; 
    FLastEdited: Nullable<TDateTime>; 
    FAVATAR: Nullable<BLOB>; 
    FMIDDLENAME: Nullable<string>; 
    FCUSTAGE: Nullable<Integer>; 
    FCUSTID: Integer; 
    FCUSTHEIGHT: Nullable<Double>; 
    FCUSTNAME: Nullable<VARCHAR(255)>; 
  public
    [Column('EMAIL', [], -1, -1, -1, '')]
    property EMAIL: Nullable<string> read FEMAIL write FEMAIL; 
    [Column('LastEdited', [], -1, -1, -1, '')]
    property LastEdited: Nullable<TDateTime> read FLastEdited write FLastEdited; 
    [Column('AVATAR', [], -1, -1, -1, '')]
    property AVATAR: Nullable<BLOB> read FAVATAR write FAVATAR; 
    [Column('MIDDLENAME', [], -1, -1, -1, '')]
    property MIDDLENAME: Nullable<string> read FMIDDLENAME write FMIDDLENAME; 
    [Column('CUSTAGE', [], -1, -1, -1, '')]
    property CUSTAGE: Nullable<Integer> read FCUSTAGE write FCUSTAGE; 
    [AutoGenerated]
    [Column('CUSTID', [cpPrimaryKey], -1, -1, -1, '')]
    property CUSTID: Integer read FCUSTID write FCUSTID; 
    [Column('CUSTHEIGHT', [], -1, -1, -1, '')]
    property CUSTHEIGHT: Nullable<Double> read FCUSTHEIGHT write FCUSTHEIGHT; 
    [Column('CUSTNAME', [], -1, -1, -1, '')]
    property CUSTNAME: Nullable<VARCHAR(255)> read FCUSTNAME write FCUSTNAME; 
  
  end;
  
implementation    
  
end.


