unit TestConsts;

interface

const
  CUSTID = 'CUSTID';
  CUSTNAME = 'CUSTNAME';
  CUSTAGE = 'CUSTAGE';
  CUSTAVATAR = 'AVATAR';
  CUSTAVATAR_LAZY = 'AVATARLAZY';
  CUST_MIDDLENAME = 'MIDDLENAME';
  CUST_STREAM = 'CUSTSTREAM';
  CUSTHEIGHT = 'CUSTHEIGHT';
  CUSTTYPE = 'CUSTTYPE';

  PRODNAME = 'PRODNAME';
  PRODPRICE = 'PRODPRICE';

  TBL_PEOPLE = 'CUSTOMERS';
  TBL_ORDERS = 'Customer_Orders';
  TBL_PRODUCTS = 'PRODUCTS';
  TBL_USERS = 'USER';
  TBL_ROLES = 'ROLE';
  TBL_CONTROLLER = 'CONTROLLER';
  TBL_SUBSIDIARY = 'SUBSIDIARY';
  TBL_REMOTE_CONNECTION = 'REMOTE_CONNECTION';

implementation

end.
