type
  TCheckSupport = DSharp.Windows.CustomPresenter.Types.TCheckSupport;
  TDragOperation = DSharp.Windows.CustomPresenter.Types.TDragOperation;
  TDropMode = DSharp.Windows.CustomPresenter.Types.TDropMode;
  TFilterDirection = DSharp.Windows.CustomPresenter.Types.TFilterDirection;
  TSelectionMode = DSharp.Windows.CustomPresenter.Types.TSelectionMode;

  TCollapsedEvent = DSharp.Windows.CustomPresenter.Types.TCollapsedEvent;
  TCompareEvent = DSharp.Windows.CustomPresenter.Types.TCompareEvent;
  TDragBeginEvent = DSharp.Windows.CustomPresenter.Types.TDragBeginEvent;
  TDragOverEvent = DSharp.Windows.CustomPresenter.Types.TDragOverEvent;
  TDragDropEvent = DSharp.Windows.CustomPresenter.Types.TDragDropEvent;
  TExpandedEvent = DSharp.Windows.CustomPresenter.Types.TExpandedEvent;
  TSelectionChangingEvent = DSharp.Windows.CustomPresenter.Types.TSelectionChangingEvent;

const
  csNone = TCheckSupport.csNone;
  csSimple = TCheckSupport.csSimple;
  csTriState = TCheckSupport.csTriState;
  csRadio = TCheckSupport.csRadio;
  doCopy = TDragOperation.doCopy;
  doMove = TDragOperation.doMove;
  doLink = TDragOperation.doLink;
  dmNowhere = TDropMode.dmNowhere;
  dmAbove = TDropMode.dmAbove;
  dmOnNode = TDropMode.dmOnNode;
  dmBelow = TDropMode.dmBelow;
  fdRootToLeafs = TFilterDirection.fdRootToLeafs;
  fdLeafsToRoot = TFilterDirection.fdLeafsToRoot;
  smSingle = TSelectionMode.smSingle;
  smLevel = TSelectionMode.smLevel;
  smMulti = TSelectionMode.smMulti;
  smNone = TSelectionMode.smNone;
